# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# IP: ip/sram_internal/sram_internal.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sram_internal || ORIG_REF_NAME==sram_internal} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_main_0_0/design_1_main_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_main_0_0 || ORIG_REF_NAME==design_1_main_0_0} -quiet] -quiet

# IP: ip/sram_internal/sram_internal.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sram_internal || ORIG_REF_NAME==sram_internal} -quiet] -quiet

# XDC: ip/sram_internal/sram_internal_ooc.xdc

# XDC: ip/sram_internal/sram_internal_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
