# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/bd/design_1/ip/design_1_main_0_0/design_1_main_0_0.xci
# IP: The module: 'design_1_main_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/ip/sram_internal/sram_internal.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sram_internal || ORIG_REF_NAME==sram_internal} -quiet] -quiet

# XDC: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/ip/sram_internal/sram_internal_ooc.xdc

# XDC: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/bd/design_1/ip/design_1_main_0_0/design_1_main_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_main_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/bd/design_1/ip/design_1_main_0_0/design_1_main_0_0.xci
# IP: The module: 'design_1_main_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/ip/sram_internal/sram_internal.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sram_internal || ORIG_REF_NAME==sram_internal} -quiet] -quiet

# XDC: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/ip/sram_internal/sram_internal_ooc.xdc

# XDC: /home/ljsch/sisdig_proyecto_final/sisdig_proyecto_final.srcs/sources_1/bd/design_1/ip/design_1_main_0_0/design_1_main_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_main_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
